# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'test' label to any change to *.spec.js files within the source dir
test:
- __tests__/**/*.spec.js


config:
- any: ['jest.config.js', 'jest.setup', 'tsconfig.json']
